---
# tasks file for port-connectivity-validator
- name: Cassandra thrift client port connectivity status
  delegate_to: '{{ inventory_hostname }}'
  wait_for:
    port: '{{ cassandra_thrift_client_port }}'
    host: '{{ private_address }}'
    timeout: 1
  register: cassandra_thrift_client_port_status
  ignore_errors: yes

- name: Cassandra JMX port connectivity status
  delegate_to: '{{ inventory_hostname }}'
  wait_for:
    port: '{{ cassandra_jmx_port }}'
    host: '{{ private_address }}'
    timeout: 1
  register: cassandra_jmx_port_status
  ignore_errors: yes

- name: Cassandra CQL Native Transport port connectivity status
  delegate_to: '{{ inventory_hostname }}'
  wait_for:
    port: '{{ cassandra_cql_native_port }}'
    host: '{{ private_address }}'
    timeout: 1
  register: cassandra_cql_native_port_status
  ignore_errors: yes

- name: Cassandra Non-SSL Gossip port connectivity status
  delegate_to: '{{ inventory_hostname }}'
  wait_for:
    port: '{{ cassandra_non_ssl_gossip_port }}'
    host: '{{ private_address }}'
    timeout: 1
  register: cassandra_non_ssl_port_status
  ignore_errors: yes
  when: cass_secure is not defined or cass_secure | bool == false